name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test account module
        run: yarn test-account --ci --coverage --maxWorkers=2

      - name: Test transaction module
        run: yarn test-transaction --ci --coverage --maxWorkers=2

      - name: Test kai-chain module
        run: yarn test-kai-chain --ci --coverage --maxWorkers=2

      - name: Test SMC module
        run: yarn test-smc --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
